# Generated by Django 4.1 on 2023-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_remove_listing_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Batrooms',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Bedrooms',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], max_length=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Cheques',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], max_length=1),
        ),
    ]
