# Generated by Django 4.1 on 2023-01-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_listing_batrooms_alter_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
