# Generated by Django 4.2.3 on 2023-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_listing_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('null', 'Null'), ('approved', 'Approved'), ('declined', 'Decline')], default='null', max_length=50),
        ),
    ]
