# Generated by Django 4.1 on 2022-11-04 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_inbox_message_chat_inbox_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_inbox',
            name='socket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
