# Generated by Django 4.1 on 2022-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='socket_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
