# Generated by Django 4.1 on 2022-11-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_socket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_inbox',
            old_name='last_message',
            new_name='message',
        ),
    ]
