# Generated by Django 4.1 on 2022-11-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_last_message_chat_inbox_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_inbox',
            name='socket_id',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='socket_id',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
