# Generated by Django 4.1 on 2022-11-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chat_inbox_socket_id_alter_message_socket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=1200),
        ),
    ]
