# Generated by Django 4.0.5 on 2022-11-29 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0008_remove_listing_is_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailabilty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Date', models.DateTimeField()),
                ('end_Date', models.DateTimeField()),
                ('start_Time', models.TimeField()),
                ('end_Time', models.TimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserAvailabilty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_Date', models.DateTimeField(auto_now_add=True)),
                ('appointment_Time', models.DateTimeField(auto_now_add=True)),
                ('is_Confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=300)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appiontment_user', to='listing.listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
