# Generated by Django 4.0.5 on 2022-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailabilty',
            name='end_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useravailabilty',
            name='start_Date',
            field=models.DateField(),
        ),
    ]
