# Generated by Django 4.1 on 2023-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_provider_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
