# Generated by Django 4.1 on 2022-11-09 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_remove_listing_is_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionair', '0006_rename_interestedqanswer_interestedanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='interestedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_user_id', to=settings.AUTH_USER_MODEL)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_user', to='listing.listing')),
            ],
        ),
    ]
