# Generated by Django 4.1 on 2022-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionair', '0007_interesteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesteduser',
            name='match_ans',
            field=models.BooleanField(default=False),
        ),
    ]
