# Generated by Django 4.1 on 2022-11-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionair', '0009_interesteduser_listing_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesteduser',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
